#! /bin/zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
    
# Aliases
alias EDITOR="emacs"

export PATH="/home/nathan/.local/bin:$PATH"

